### ISSUE TITLE
Compilation hangs when setting `-coverage -O2` with gcc

### ISSUE THREAD

**Issue by jimhester** [jgm/cmark#121] opened 2016-04-19 13:31 UTC
I have the gcc compilers installed locally as gcc-5 and g++-5. The following build options result in the compilation hanging when trying to build scanners.c.o.

```bash
mkdir build && cd build
cmake .. -DCMAKE_C_COMPILER="gcc-5" -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_C_FLAGS_DEBUG="-O2 -coverage" -DCMAKE_CXX_FLAGS_DEBUG="-O2 -coverage" -DCMAKE_BUILD_TYPE=Debug
make VERBOSE=1
```
Turning off optimizations by compiling with `-O0 -coverage` works fine however, as do all optimization levels with clang.

@jeroenooms and I uncovered this situation when trying to compute code coverage for the R bindings at https://github.com/jeroenooms/commonmark/pull/5

I am not sure if this is a commonmark issue or a gcc bug.

**Comment by nwellnhof** [comment] 2016-04-19 15:57
Yeah, I noticed that a while ago. This is caused by a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64928).

**Comment by jgm** [comment] 2016-04-19 16:23
No idea. scanners.c is automatically generated by re2c.
So, this *could* also be an re2c bug.

+++ Jim Hester [Apr 19 16 06:31 ]:

**Comment by nwellnhof** [comment] 2016-05-10 17:57
I'm pretty sure it's this GCC bug. As [noted in the thread](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64928#c9), the problem disappears if you compile with `-fno-tree-loop-im`.

**Comment by jgm** [comment] 2016-05-14 04:19
If it's a gcc bug, then I think we should close this issue.

**Closed by jgm** 2016-05-14 04:19 UTC
